#!/usr/bin/env node
// Scrape an og:image / twitter:image for each place from its own website and
// write src/data/placeImages.ts (slug -> image URL). Free, no API key.
//
// Policy: we only record the image the venue itself chose to represent its page
// (og:image / twitter:image). We never fabricate. ~2/3 of sites expose one; the
// rest are simply omitted and fall back to the generated card gradient in the UI.
//
// Usage:
//   node scripts/scrape-images.mjs           # scrape all, merge with existing
//   node scripts/scrape-images.mjs --limit 20 --dry   # sample, don't write
//
// External URLs are hotlinked and rendered with <img onError> fallback, so a
// dead/blocked image degrades gracefully. Re-run periodically to refresh.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const PLACES = path.join(ROOT, "src/data/places.ts");
const OUT = path.join(ROOT, "src/data/placeImages.ts");

const args = process.argv.slice(2);
const DRY = args.includes("--dry");
const LIMIT = args.includes("--limit")
  ? parseInt(args[args.indexOf("--limit") + 1], 10)
  : Infinity;
const CONCURRENCY = 12;
const TIMEOUT_MS = 9000;

const HEADERS = {
  "user-agent":
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0 Safari/537.36",
  accept: "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
  "accept-language": "en-US,en;q=0.9",
};

// slug -> website, parsed by splitting on the `slug: "` anchor so each block
// is bounded to a single place object (website is optional and stays in-block).
function parsePlaces() {
  const src = fs.readFileSync(PLACES, "utf8");
  const blocks = src.split(/\n\s*slug:\s*"/).slice(1);
  const out = [];
  for (const b of blocks) {
    const slug = b.match(/^([^"]+)"/)?.[1];
    const website = b.match(/\n\s*website:\s*"([^"]+)"/)?.[1];
    if (slug && website) out.push({ slug, website });
  }
  return out;
}

const BAD = /favicon|apple-touch|-icon|\/icon[.\-]|\.svg(\?|$)/i;

function extractImage(html, baseUrl) {
  const m =
    html.match(
      /<meta[^>]+(?:property|name)=["'](?:og:image(?::secure_url)?|twitter:image(?::src)?)["'][^>]+content=["']([^"']+)["']/i
    ) ||
    html.match(
      /<meta[^>]+content=["']([^"']+)["'][^>]+(?:property|name)=["'](?:og:image|twitter:image)["']/i
    );
  if (!m) return null;
  let url = m[1].trim();
  if (!url || url.startsWith("data:")) return null;
  try {
    url = new URL(url, baseUrl).href; // resolve relative
  } catch {
    return null;
  }
  if (BAD.test(url)) return null;
  return url;
}

async function fetchImage(website) {
  const controller = new AbortController();
  const t = setTimeout(() => controller.abort(), TIMEOUT_MS);
  try {
    const r = await fetch(website, {
      headers: HEADERS,
      redirect: "follow",
      signal: controller.signal,
    });
    if (!r.ok) return { status: r.status, url: null };
    const html = await r.text();
    return { status: 200, url: extractImage(html, r.url || website) };
  } catch (e) {
    return { status: 0, url: null, err: e.name };
  } finally {
    clearTimeout(t);
  }
}

async function main() {
  const places = parsePlaces().slice(0, LIMIT);
  // Preserve any previously-scraped images so a re-run only fills gaps + refreshes.
  let existing = {};
  if (fs.existsSync(OUT)) {
    const prev = fs.readFileSync(OUT, "utf8");
    for (const m of prev.matchAll(/"([^"]+)":\s*"([^"]+)"/g)) existing[m[1]] = m[2];
  }

  const result = { ...existing };
  let ok = 0,
    blocked = 0,
    noog = 0,
    err = 0,
    done = 0;

  const queue = [...places];
  async function worker() {
    for (;;) {
      const item = queue.shift();
      if (!item) return;
      const { status, url } = await fetchImage(item.website);
      done++;
      if (url) {
        result[item.slug] = url;
        ok++;
      } else if (status >= 400) blocked++;
      else if (status === 0) err++;
      else noog++;
      if (done % 25 === 0)
        process.stderr.write(
          `  ${done}/${places.length}  ok=${ok} blocked=${blocked} noog=${noog} err=${err}\n`
        );
    }
  }
  await Promise.all(Array.from({ length: CONCURRENCY }, worker));

  console.log(
    `\nDone ${done}: ok=${ok} blocked=${blocked} noog=${noog} err=${err} | total images=${Object.keys(result).length}`
  );

  if (DRY) {
    console.log("--dry: not writing.");
    return;
  }

  const sorted = Object.keys(result).sort();
  const body =
    "// AUTO-GENERATED by scripts/scrape-images.mjs — do not edit by hand.\n" +
    "// slug -> og:image/twitter:image scraped from each place's own website.\n" +
    "// Rendered with <img onError> fallback, so dead/blocked URLs degrade gracefully.\n\n" +
    "export const placeImages: Record<string, string> = {\n" +
    sorted.map((s) => `  ${JSON.stringify(s)}: ${JSON.stringify(result[s])},`).join("\n") +
    "\n};\n";
  fs.writeFileSync(OUT, body);
  console.log(`Wrote ${OUT} (${sorted.length} images).`);
}

main();
